In [1]:
import os

os.getcwd()

'd:\\Zayaan\\D_git\\ai-ml-da\\ml\\zayaans-ml\\nn-from-scratch'

In [2]:
import numpy as np
import pandas as pd


df = pd.read_csv("healthcare-dataset-stroke-data.csv")

In [8]:
df = df[["age", "avg_glucose_level", "bmi", "stroke"]]

In [9]:
df

        age  avg_glucose_level   bmi     stroke
index
1      67.0             228.69  36.6     Stroke
2      80.0             105.92  32.5     Stroke
3      49.0             171.23  34.4     Stroke
4      79.0             174.12  24.0     Stroke
5      81.0             186.21  29.0     Stroke
...     ...                ...   ...        ...
4905   13.0             103.08  18.6  No Stroke
4906   81.0             125.20  40.0  No Stroke
4907   35.0              82.99  30.6  No Stroke
4908   51.0             166.29  25.6  No Stroke
4909   44.0              85.28  26.2  No Stroke

[4909 rows x 4 columns]

In [10]:
df = df.replace(1, "Stroke")
df = df.replace(0, "No Stroke")

df = df.dropna(subset=["bmi"])

df["age"] = pd.to_numeric(df["age"], errors="coerce")
df = df.dropna(subset=["age"])

In [11]:
df

        age  avg_glucose_level   bmi     stroke
index
1      67.0             228.69  36.6     Stroke
2      80.0             105.92  32.5     Stroke
3      49.0             171.23  34.4     Stroke
4      79.0             174.12  24.0     Stroke
5      81.0             186.21  29.0     Stroke
...     ...                ...   ...        ...
4905   13.0             103.08  18.6  No Stroke
4906   81.0             125.20  40.0  No Stroke
4907   35.0              82.99  30.6  No Stroke
4908   51.0             166.29  25.6  No Stroke
4909   44.0              85.28  26.2  No Stroke

[4904 rows x 4 columns]

In [12]:
df.value_counts("stroke")

stroke
No Stroke    4695
Stroke        209
Name: count, dtype: int64

In [13]:
df.to_csv("./stroke.csv")